name: coin_exchange
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.5
  flutter_bloc: ^7.0.0
  flutter_phoenix: ^1.0.0
  animation_wrappers: ^0.0.4
  cupertino_icons: ^1.0.3
  google_mobile_ads: ^0.13.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"


flutter_launcher_name:
  name: "Coin Exchange"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appIcon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Currency/
    - assets/Home/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf

